[repository]
name = "hypr-radiant"
authors = ["Nika Sumbadze (@nsumbadze)"]
commit_pins = [
    ["39d7e209c79d451efab1b21151d5938289da838d", "eeaa9d3417cb3b34f7a4aa3dc8deac10506dd46e"]
]

[hypr-radiant]
description = "Native workspace overview with live previews, gestures, and search."
authors = ["Nika Sumbadze (@nsumbadze)"]
output = "build/hypr-radiant.so"
build = [
    "cmake -S . -B build -DCMAKE_BUILD_TYPE=Release",
    "cmake --build build"
]
